apiVersion: v1
kind: Pod
metadata:
  name: user-input-pod
  labels:
    name: user-input-pod
    app: user-login-app
spec:
  containers:
    - name: user-input
      image: adarsha/kub_demo_app
      ports:
        - containerPort: 8080