apiVersion: v1
kind: Pod
metadata:
  name: user-input
  labels:
    name: user-input-pod
    app: user-login-app
spec:
  containers:
    - name: demo-app
      image: adarsha/kub_demo_app:3.0
      ports:
        - containerPort: 8080